#
# Data Hub Configuration
#

helixConfig:
    #
    # Datagrid Configuration
    #
    nodeId: "NODE-0"

    # For Redis Stand-Alone (Single-Node) enter a single host below
    datagridHostsA:
      - "redis://192.168.0.6:6379"
    #  - "redis://192.168.0.6:7000"
    #  - "redis://192.168.0.6:7001"
    #  - "redis://192.168.0.6:7002"
    # For Redis Stand-Alone (Single-Node) enter a single host below
    datagridHostsB:
      - "redis://192.168.0.6:6380"
    #  - "redis://192.168.0.6:7000"
    #  - "redis://192.168.0.6:7001"
    #  - "redis://192.168.0.6:7002"

    #
    # Jedis Pool Configuration
    #
    maxTotal: 1024                   # connections (used to be 30)
    maxIdle: 1024                    # connections
    minIdle: 1024                    # connections
    minEvictableIdleTimeMillis: 60000    # ms
    timeBetweenEvictionRunsMillis: 30000 # ms	
    blockWhenExhausted: true
    maxWaitMillis: 2000             # ms
    testWhileIdle: true
    testOnBorrow: true              # Must be set to true for DataHub
    testOnReturn: false

    #
    # Datagrid Connection Configuration
    #
    healthCheckerHeadStartMillis: 500
    millisToWaitBeforeConnectionRetry: 2000
    maxNumberOfConnectionRetries: 150
    datagridHealthCheckChannelName: "/datagrid/healthchecker"
    
    #
    # Replication Configuration
    #
    replicationRole: "A"         # One of: "A", "B", "NONE"
    replicationTopicNameRoot: ".datagrid.replication.topic"
    replicationTopicNumberOfPartitions: 1
    replicationTopicReplicationFactor: 1
    replicationTopicRetentionMs: 3600000    # 1 hour
    replicationHosts: "192.168.0.6:9092"
    # replicationHosts: "192.168.0.6:9092,192.168.0.6:9093,192.168.0.6:9094"
    replicationQueueName: "/datagrid/replication/queue"
    replicationTopicMonitorBoundry: 25      # 0 - no monitoring
    replicationQueueMonitorBoundry: 25      # 0 - no monitoring
    
    #
    # User Management Config
    #
    userMapDgKey: "/datagrid/users"
    autoCreateUsers: true
    superAdminId: "superadmin"
    
    #
    # JWT Token validation parameters
    #
    jwtAuthEnabled: true
    publicKeyHs: "abcdefghi123456789"
    publicKeyRsa: "-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnzyis1ZjfNB0bBgKFMSvvkTtwlvBsaJq7S5wA+kzeVOVpVWwkWdVha4s38XM/pa/yr47av7+z3VTmvDRyAHcaT92whREFpLv9cj5lTeJSibyr/Mrm/YtjCZVWgaOYIhwrXwKLqPr/11inWsAkfIytvHWTxZYEcXLgAXFuUuaS3uF9gEiNQwzGTU1v0FqkqTBr4B8nW3HCN47XUu0t8Y0e+lf4s4OxQawWD79J9/5d3Ry0vbV3Am1FtGJiJvOwRsIfVChDpYStTcHTCMqtvWbV6L11BWkpzGXSW4Hv43qa+GSYOD2QU68Mb59oSk2OB+BtOLpJofmbGEGgvmwyCI9MwIDAQAB-----END PUBLIC KEY-----"
    userIdClaimName: "userId"

    #
    # Session Management Config
    #
    sessionsTimingAccuracySeconds: 5
    sessionMapDgKey: "/datagrid/sessions/map"
    sessionExpirySetDgKey: "/datagrid/sessions/expiryset"    
    sessionExpiryQueueDgKey: "/datagrid/sessions/expiryqueue"
    sessionExpiryChannelDgKey: "/datagrid/sessions/expirychannel"
    
    #
    # Data Management Config
    #
    userDataMapDgKey: "/datagrid/users/%s/data" # userId is injected
    dataChangeChannelDgKey: "/datagrid/data/datachangechannel"
    
    #
    # Subscription Management Config
    #
    userProducerSubscriptionsSetDgKey: "/datagrid/subscriptions/users/%s/producers/%s" # userId & producerId are injected
    sessionSubscriptionsSetDgKey: "/datagrid/subscriptions/sessions/%s" # csid is injected
    
sessionTimeToLiveSeconds: 600          # seconds

logging:
  level: INFO
  loggers:
    org.apache.kafka: WARN
    solutions.forcloud: INFO
    solutions.forcloud.helix4j: INFO
    solutions.forcloud.helix4j.datamodel: INFO    
    solutions.forcloud.helix4j.modules.replication: INFO
    solutions.forcloud.helix4j.datahub: INFO
  appenders:
    - type: console
      queueSize: 2048
      threshold: DEBUG
      timeZone: UTC
      logFormat: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [Thread-%t] %logger{0} - %m%n"
      # This does not work as in log4f.properties:
      # logFormat: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [Thread-%t] %c{1}.%M(line:%L) - %m%n"
    - type: file
      threshold: DEBUG
      timeZone: UTC
      logFormat: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [Thread-%t] %logger{0} - %m%n"
      # This does not work as in log4f.properties:
      # logFormat: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [Thread-%t] %c{1}.%M(line:%L) - %m%n"
      currentLogFilename: /tmp/data-hub.log
      archivedLogFilenamePattern: /tmp/data-hub-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      maxFileSize: 10MiB

# use the simple server factory if you only want to run on a single port
server:
  type: simple
  # applicationContextPath: /application
  # adminContextPath: /admin
  applicationContextPath: /data-hub
  adminContextPath: /data-hub/admin
  rootPath: /api
  connector:
    type: http
    port: 9090
  requestLog:
    appenders: []
    # appenders:
      # - type: console

# server:
  #  softNofileLimit: 1000
  #  hardNofileLimit: 1000
  # applicationConnectors:
    # - type: http
      # port: 8080
    # - type: https
      # port: 8443
      # keyStorePath: example.keystore
      # keyStorePassword: example
    # #this requires the alpn-boot library on the JVM's boot classpath
    # #- type: h2
    # #  port: 8445
    # #  keyStorePath: example.keystore
    # #  keyStorePassword: example
  # adminConnectors:
    # - type: http
      # port: 8081
    # - type: https
      # port: 8444
      # keyStorePath: example.keystore
      # keyStorePassword: example
